### ISSUE TITLE
TypeError: Incorrect value for stdio stream: inherit

### ISSUE THREAD

**Issue by Subby4Git** [TechnologyAdvice/DevLab#13]
Hi,

I followed the README, and cloned the demo app.

However, when I run 'lab install', I run into the following error - everytime.

#> Starting service devlab_mongodb_puretech_1446502746915
---
!> Failed to start devlab_mongodb_puretech_1446502746915
!> TypeError: Incorrect value for stdio stream: inherit
!> Error running  npm run test;, exited with code 1
#> Stoping service: devlab_mongodb_puretech_1446502746915

Can you please help with this issue. I am running this on Koding.com

**Comment by Fluidbyte** [comment]
What version of Node are you running?

**Comment by Subby4Git** [comment]
I ran node version 5 (latest) from docker

**Comment by Fluidbyte** [comment]
I'm not really sure, the only issue I can find (and replicate) is `spawn` on older versions of Node. I'm assuming you checked with `node -v` to ensure you're running 0.12?

**Comment by TomFrost** [comment]
@Subby4Git I believe @Fluidbyte meant your local node version (responsible for running DevLab), not the container version in the devlab.yml file.

**Comment by Subby4Git** [comment]
Oh, thanks for the clarification @TomFrost! I had misunderstood it for the devlab container version. 
I will look into it and let you know of the result.

**Comment by Fluidbyte** [comment]
Closing. Docs in the README on preventing this error.
