### ISSUE TITLE
How is this different than docker-compose?

### ISSUE THREAD

**Issue by tback** [TechnologyAdvice/DevLab#14]
I feel slightly silly asking this. Anyway: How is this different than docker-compose apart from being implemented in nodejs instead of python?

https://docs.docker.com/compose/

**Comment by Fluidbyte** [comment]
We get this question a lot, so probably good to answer in an issue so we can reference. @TomFrost posted a comment [here](https://news.ycombinator.com/item?id=10482991) that covered this really well:

> Compose is actually part of the reason we wrote this tool. We tried so hard to make it make sense for a TDD workflow, but it was always cumbersome.
Compose wants you to build your application into a container, and build and run that container every time you have a task to run. This takes time and a fair amount of cleanup, especially when you want a clean environment to run your tests that doesn't persist to the next run. DevLab just wants you to specify the environment to plug your application into, and doesn't build a container at all.
The result is:
- No manual cleanup
- No pile of images or processes that stack up
- Your project doesn't have to be a Docker project. It doesn't need a Dockerfile. You can use this for something you plan to clone on an EC2 node and run from an upstart script.
- No Vagrant/Ansible/Chef/Puppet, server config, anything. You pick out an image that matches your environment's needs (node:4.2, wordpress, go, etc., hub.docker.com is a great place to start) and DevLab plugs your app into it.
- More development-oriented features outside of the pure Docker ecosystem that Compose stays confined to. For example, soon, Mac users running docker-machine will get to enjoy ports bound to localhost much like Linux docker users do [1].
To get this functionality outside of Compose, we had a monolithic makefile to maintain all of this for us. It wasn't DRY and it wasn't smooth. I hope you enjoy DevLab!

In general the goal was to overcome some issues we had internally with Compose. We also are building on this concepts of Compose to add things such as:

* [`-f` flag](https://github.com/TechnologyAdvice/DevLab#from) to allow for runtime environment changes
* SSH tunneling to allow use of `localhost` on systems running [docker-machine](https://docs.docker.com/machine/)
* Individualized tasks which can be [referenced/aliased](https://github.com/TechnologyAdvice/DevLab#running-multiple-tasks) to more easily control task sets

Ultimately we liked Compose, we just felt that there were some things missing inherently from it's design/purpose and wanted to build a tool that would make it extremely simple for developers to be able to containerize their workflow, with or without prior knowledge of Docker.

**Comment by levithomason** [comment]
Seems this is resolved, cleaning up.  Feel free to open again if anything was overlooked.

**Comment by polarathene** [comment]
Just came across this issue myself looking for the same answer, might help to reference it or the link to Hacker News on the repo ReadMe.
