### ISSUE TITLE
If persistence is on, DevLab doesn't reconnect to an existing mongodb container.

### ISSUE THREAD

**Issue by Narquadah** [TechnologyAdvice/DevLab#15]
If I try to use DevLab with a persistent Mongodb it doesn't work. It seems to not stop the running Container when I quit the current task.

```
Error response from daemon: Cannot start container 7fd10af6ac5bf34a53d7a7cf525dc0673457b76cf082d1461ca4f8f5a5354b03: failed to create endpoint devlab_mongodb_username_1447779638533 on network bridge: Bind for 0.0.0.0:27017 failed: port is already allocated
```

**Comment by Fluidbyte** [comment]
I've confirmed this issue, to resolve we need to have services use non-unique names when they are started with `persist: true`

**Comment by Fluidbyte** [comment]
Just pushed [v.1.5.2](https://github.com/TechnologyAdvice/DevLab/releases/tag/v1.5.2) which should resolve this issue.

**Comment by Narquadah** [comment]
It's working fine now thx!
