### ISSUE TITLE
Dump Logs from Failing Service Start

### ISSUE THREAD

**Issue by Fluidbyte** [TechnologyAdvice/DevLab#41]
Currently when a service startup fails or a link cannot be completed the process simply exits with no explanation of the error. Need to dump any error messages so problem can be triaged and corrected.

**Comment by Atsman** [comment]
Hello,

I use your project and first thing i notice is that there is no output in console if something wrong.
For local development i fixed that in global node_modules, by just changing silent argument to false.
I don't know, maybe there is exists more elegant solution to this. What do you think?

Best regards,
Aleh

**Comment by Fluidbyte** [comment]
As ref'd in #51 I'd like to propose we have any failing services report themselves, e.g.

```
The following service(s) failed to start: dl_mongo_Gf89a87
```

The output from docker itself doesn't give you any really useful information, so this would allow you to view logs for the failed containers.
