### ISSUE TITLE
`lab` cli tool name clashes with HapiJS lab unit testing tool

### ISSUE THREAD

**Issue by meister** [TechnologyAdvice/DevLab#46]
There is already `lab` cli tool from Hapi so the names conflict and one will render the other unusable. Perhaps it makes sense to not use the same bin property as they do, as their NPM package name also matches their CLI command.

Reference: https://github.com/hapijs/lab

**Comment by Fluidbyte** [comment]
Interesting, I don't recall seeing this when we decided to use the `lab` command but it has been around for awhile so I probably just missed it.

The big issue is (for our team at least) the `lab` command is our standard. Changing this would essentially be a major version (breaking) release, and I like the shorthand version.

I'll need to toy around with this, I'm wondering if we could build in something to handle this safely.

**Comment by Fluidbyte** [comment]
At this point I'm going to leave things the way they are. This is a possibility down the road for a major version release, but collisions could occur with local aliases or other (unknown) applications as `lab` is a short command I could see being used for a myriad of things.
